name: tests

on:
  push:
  pull_request:
    branches: [$default-branch]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: upload to server
        working-directory: ./apps/vite/
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 在 Secrets 中添加你的服务器 IP
          username: ${{ secrets.SERVER_USER }} # 在 Secrets 中添加你的服务器用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets 中的 SSH 私钥
          port: 22 # SSH 端口，默认为 22
          source: "./dist" # 本地文件路径
          target: "/home/www" # 服务器上的目标路径
